version: '3.7'
services:
  postgresql:
    image: postgres
    container_name: pg-docker
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    restart: always